name: despliegue

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Build
        run: |
          git clone https://github.com/Ardilan13/maquinas.git
          git checkout develop
          git pull